plugins {
    id 'com.android.application'
}

android {
    namespace 'uk.tatrycupcio.communityforall'
    compileSdk 36

    defaultConfig {
        applicationId 'uk.tatrycupcio.communityforall'
        minSdk 24
        targetSdk 36
        versionCode 5
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('community-for-all.jks')
            storePassword System.getenv('KEYSTORE_PASSWORD')
            keyAlias System.getenv('KEY_ALIAS')
            keyPassword System.getenv('KEY_PASSWORD')
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
