name: Build Android App Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Android App Bundle
        run: gradle bundleRelease

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: community-for-all-aab
          path: app/build/outputs/bundle/release/app-release.aab
